# Generated by Django 2.1.7 on 2019-03-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50)),
                ('teachername', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Classnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notename', models.CharField(max_length=200)),
                ('notecontent', models.TextField()),
                ('notetime', models.DateTimeField(auto_now_add=True)),
                ('noteupdatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=200)),
                ('examscore', models.IntegerField()),
                ('examtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkname', models.CharField(max_length=200)),
                ('homeworkscore', models.CharField(max_length=50)),
                ('homeworktime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentid', models.IntegerField()),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Classes')),
                ('studentcourse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Courses')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='homeworkstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
        migrations.AddField(
            model_name='exams',
            name='examstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
    ]
