# Generated by Django 2.1.7 on 2019-03-31 06:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=50)),
                ('teachername', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Classnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notename', models.CharField(max_length=200)),
                ('notecontent', ckeditor_uploader.fields.RichTextUploadingField()),
                ('notetime', models.DateTimeField(auto_now_add=True)),
                ('noteupdatetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=200)),
                ('examscore', models.IntegerField()),
                ('examtime', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-examtime'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeworkname', models.CharField(max_length=200)),
                ('homeworkscore', models.CharField(max_length=50)),
                ('homeworktime', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-homeworktime'],
            },
        ),
        migrations.CreateModel(
            name='onlinetestgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='onlinetestlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=200)),
                ('listgrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestgrade')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField()),
                ('questiontext', models.ImageField(upload_to='questions')),
                ('questionanswer', models.CharField(max_length=50)),
                ('questiongrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestgrade')),
                ('questiontestlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestlist')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testscore', models.IntegerField()),
                ('scoreid', models.CharField(max_length=100)),
                ('scorename', models.CharField(max_length=100)),
                ('scoretime', models.DateTimeField(auto_now_add=True)),
                ('scoreupdatetime', models.DateTimeField(auto_now=True)),
                ('correctpercent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('testamount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('studentid', models.IntegerField()),
                ('studentclass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Classes')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='homeworkstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
        migrations.AddField(
            model_name='exams',
            name='examstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
    ]
