# Generated by Django 2.1.7 on 2019-03-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlinetestgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='onlinetestlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=200)),
                ('listgrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestgrade')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.CharField(max_length=500)),
                ('questionanswer', models.CharField(max_length=50)),
                ('questiongrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestgrade')),
                ('questiontestlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestlist')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testscore', models.IntegerField()),
                ('scoretime', models.DateTimeField(auto_now_add=True)),
                ('scoreid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.onlinetestlist')),
                ('scorename', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students')),
            ],
        ),
        migrations.AlterModelOptions(
            name='exams',
            options={'ordering': ['-examtime']},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-homeworktime']},
        ),
    ]
