# Generated by Django 2.1.7 on 2019-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0002_auto_20190306_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionid',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='questiontext',
            field=models.ImageField(upload_to='questions'),
        ),
    ]
