# Generated by Django 2.1.7 on 2019-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0003_auto_20190306_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scoreid',
            field=models.CharField(max_length=100),
        ),
    ]
