# Generated by Django 2.1.7 on 2019-04-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0003_auto_20190402_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homeworkstudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
    ]
