# Generated by Django 2.1.7 on 2019-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0004_auto_20190309_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='scorename',
            field=models.CharField(max_length=100),
        ),
    ]
