# Generated by Django 2.1.7 on 2019-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0004_auto_20190402_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchstudentid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('student', models.CharField(max_length=200)),
                ('studentid', models.IntegerField()),
            ],
        ),
    ]
