# Generated by Django 2.1.7 on 2019-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0005_searchstudentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnotes',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchstudentid',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
