# Generated by Django 2.1.7 on 2019-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0005_auto_20190309_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='scoreupdatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
