# Generated by Django 2.1.7 on 2019-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0006_scores_scoreupdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='studentcourse',
        ),
        migrations.AddField(
            model_name='scores',
            name='correctpercent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scores',
            name='testamount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
