# Generated by Django 2.1.7 on 2019-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0007_loginrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'ordering': ['-lastlogintime']},
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='lastlogintime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='logincount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
