# Generated by Django 2.1.7 on 2019-03-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0007_auto_20190317_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='correctpercent',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
