# Generated by Django 2.1.7 on 2019-03-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0008_auto_20190317_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='examtime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworktime',
            field=models.CharField(max_length=200),
        ),
    ]
