# Generated by Django 2.1.7 on 2019-04-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0008_auto_20190409_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classingss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200)),
                ('classscore', models.CharField(max_length=200)),
                ('classtime', models.DateTimeField(auto_now_add=True)),
                ('classstudent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students')),
            ],
            options={
                'ordering': ['-classtime'],
            },
        ),
        migrations.AlterField(
            model_name='loginrecord',
            name='logincount',
            field=models.IntegerField(default=0),
        ),
    ]
