# Generated by Django 2.1.7 on 2019-03-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0009_auto_20190319_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnotes',
            options={'ordering': ['-notetime']},
        ),
    ]
