# Generated by Django 2.1.7 on 2019-04-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0009_auto_20190409_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aacount', models.IntegerField(default=0)),
                ('acount', models.IntegerField(default=0)),
                ('bcount', models.IntegerField(default=0)),
                ('ccount', models.IntegerField(default=0)),
                ('dcount', models.IntegerField(default=0)),
                ('ecount', models.IntegerField(default=0)),
                ('fcount', models.IntegerField(default=0)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students')),
            ],
        ),
    ]
