# Generated by Django 2.1.7 on 2019-03-31 03:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0010_auto_20190330_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classnotes',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='classnotes',
            name='notecontent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
