# Generated by Django 2.1.7 on 2019-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0010_homeworksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksum',
            name='lastlogintime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
