# Generated by Django 2.1.7 on 2019-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0012_auto_20190411_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('gdtime', models.CharField(max_length=200)),
                ('phone1', models.BigIntegerField()),
                ('phone2', models.BigIntegerField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addtime'],
            },
        ),
        migrations.AlterModelOptions(
            name='exams',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='homeworksum',
            options={'ordering': ['-lasttime']},
        ),
    ]
