# Generated by Django 2.1.7 on 2019-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0013_auto_20190617_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txl',
            name='phone2',
            field=models.BigIntegerField(default=0),
        ),
    ]
