# Generated by Django 2.1.7 on 2019-09-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0014_auto_20190617_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='guoguan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornot', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='guoguanname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idd', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'get_latest_by': ['homeworktime'], 'ordering': ['-homeworktime']},
        ),
        migrations.AlterField(
            model_name='txl',
            name='phone2',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='guoguan',
            name='guoguan_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.guoguanname'),
        ),
        migrations.AddField(
            model_name='guoguan',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
        ),
    ]
