# Generated by Django 2.1.7 on 2019-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0015_auto_20190912_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guoguan',
            name='ornot',
            field=models.CharField(max_length=100),
        ),
    ]
