# Generated by Django 2.1.7 on 2019-09-17 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0016_auto_20190912_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='rankq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenlei', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students')),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.AlterModelOptions(
            name='guoguan',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='guoguan',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
