# Generated by Django 2.1.7 on 2019-09-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0017_auto_20190917_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='addrankqdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
