# Generated by Django 2.1.7 on 2019-09-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0018_addrankqdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrankqdetail',
            name='name',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students'),
            preserve_default=False,
        ),
    ]
