# Generated by Django 2.1.7 on 2019-09-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0019_addrankqdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrankqdetail',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
