# Generated by Django 2.1.7 on 2019-09-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0020_auto_20190918_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='badhomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time0', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('stu_id', models.CharField(max_length=100)),
                ('ms', models.CharField(max_length=200)),
                ('ornot', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mylearn.Students')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
