# Generated by Django 2.1.7 on 2019-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0021_badhomework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wkqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('questiontext', models.ImageField(upload_to='questions')),
                ('questionanswer', models.CharField(max_length=50)),
            ],
        ),
    ]
