# Generated by Django 2.1.7 on 2019-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0022_wkqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yuxiname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ornot', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
