# Generated by Django 2.1.7 on 2019-10-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0023_yuxiname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
