# Generated by Django 2.1.7 on 2019-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0025_auto_20191005_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuxiname',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
