# Generated by Django 2.1.7 on 2019-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0026_auto_20191006_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('ornot', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='badhomework',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='yuxitestcount',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
