# Generated by Django 2.1.7 on 2019-10-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0027_auto_20191006_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='wkqs',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
