# Generated by Django 2.1.7 on 2019-10-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0028_wkqs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xxqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num0', models.IntegerField()),
                ('num1', models.IntegerField()),
                ('yunsuan', models.IntegerField()),
            ],
        ),
    ]
