# Generated by Django 2.1.7 on 2019-10-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0030_xxqs_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxqs',
            name='ornot',
            field=models.IntegerField(default=0),
        ),
    ]
