# Generated by Django 2.1.7 on 2019-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0032_wkqs_wrongcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wkqs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('questiontext', models.ImageField(upload_to='questions')),
                ('questionanswer1', models.CharField(max_length=50)),
                ('questionanswer2', models.CharField(max_length=50)),
                ('wrongcount', models.IntegerField(default=0)),
            ],
        ),
    ]
