# Generated by Django 2.1.7 on 2019-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0033_wkqs2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wktestlimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('limit', models.IntegerField()),
            ],
        ),
    ]
