# Generated by Django 2.1.7 on 2019-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0034_wktestlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuxiname',
            name='costtime',
            field=models.IntegerField(default=0),
        ),
    ]
