# Generated by Django 2.1.7 on 2019-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0035_yuxiname_costtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='wkqs2',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
