# Generated by Django 2.1.7 on 2019-10-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0036_wkqs2_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('testrm', models.ImageField(upload_to='questions')),
            ],
        ),
    ]
