# Generated by Django 2.1.7 on 2019-10-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0037_testrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='wktestlimit',
            name='chances',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
