# Generated by Django 2.1.7 on 2019-10-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0038_wktestlimit_chances'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuxitestcount',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
