# Generated by Django 2.1.7 on 2019-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0039_yuxitestcount_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yuxitestcount',
            name='seconds',
            field=models.BigIntegerField(default=0),
        ),
    ]
