# Generated by Django 2.1.7 on 2019-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0041_wkqs3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wkqs4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('questiontext', models.CharField(max_length=500)),
                ('questionanswer1', models.CharField(max_length=50)),
                ('questionanswer2', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='wkqs',
            name='wrongcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wkqs2',
            name='category',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='wkqs3',
            name='category',
            field=models.IntegerField(default=3),
        ),
    ]
