# Generated by Django 2.1.7 on 2019-11-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0042_auto_20191101_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wkqs4',
            name='jid',
        ),
        migrations.RemoveField(
            model_name='wkqs4',
            name='zid',
        ),
    ]
