# Generated by Django 2.1.7 on 2019-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0043_auto_20191101_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='wkqs4',
            name='jid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wkqs4',
            name='zid',
            field=models.IntegerField(default=0),
        ),
    ]
