# Generated by Django 2.1.7 on 2019-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0044_auto_20191102_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xxdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('kaoqin', models.IntegerField()),
                ('kaohui', models.IntegerField()),
                ('shijia', models.IntegerField()),
                ('bingjia', models.IntegerField()),
                ('hunjia', models.IntegerField()),
                ('sangjia', models.IntegerField()),
                ('chanjia', models.IntegerField()),
                ('hulijia', models.IntegerField()),
                ('summ', models.IntegerField()),
            ],
        ),
    ]
