# Generated by Django 2.1.7 on 2020-02-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0045_xxdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='XHL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classs', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-addtime'],
            },
        ),
    ]
