# Generated by Django 2.1.7 on 2020-02-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0048_auto_20200207_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newnames0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yuxiname0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ornot', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('costtime', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Yuxitestcount0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
