# Generated by Django 2.1.7 on 2020-02-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0049_newnames0_yuxiname0_yuxitestcount0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wktestlimit0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('chances', models.IntegerField()),
            ],
        ),
    ]
