# Generated by Django 2.1.7 on 2020-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0052_xxqs22_xxqs23_xxqs24'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rankxhl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('costtime', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
