# Generated by Django 2.1.7 on 2020-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0054_lasttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankxhl',
            options={'ordering': ['-costtime']},
        ),
        migrations.AddField(
            model_name='lasttime',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
