# Generated by Django 2.1.7 on 2020-02-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0055_auto_20200209_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zkfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('id1', models.IntegerField()),
                ('questiontext', models.ImageField(upload_to='questions')),
                ('questionanswer', models.CharField(max_length=50)),
                ('wrongcount', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='rankxhl',
            options={'ordering': ['costtime']},
        ),
    ]
