# Generated by Django 2.1.7 on 2020-02-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0056_auto_20200210_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkfx',
            name='id2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zkfx',
            name='id3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
