# Generated by Django 2.1.7 on 2020-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0057_auto_20200210_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zktishu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField()),
                ('id3', models.IntegerField()),
                ('ts', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='zkfx',
            name='id2',
        ),
        migrations.RemoveField(
            model_name='zkfx',
            name='id3',
        ),
    ]
