# Generated by Django 2.1.7 on 2020-02-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0058_auto_20200210_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zkfx',
            old_name='id0',
            new_name='id2',
        ),
        migrations.RenameField(
            model_name='zkfx',
            old_name='id1',
            new_name='id3',
        ),
        migrations.AddField(
            model_name='zktishu',
            name='zs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
