# Generated by Django 2.1.7 on 2020-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0059_auto_20200210_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yuxinamezk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zid', models.IntegerField()),
                ('jid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('ornot', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('fs', models.CharField(max_length=200)),
                ('costtime', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='zkfx',
            name='wrongcount',
            field=models.IntegerField(default=0),
        ),
    ]
