# Generated by Django 2.1.7 on 2020-02-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0060_auto_20200211_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelimitzk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('id1', models.IntegerField()),
                ('limit1', models.IntegerField()),
                ('limit2', models.IntegerField()),
                ('limit3', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='zktishu',
            name='zs',
            field=models.IntegerField(default=0),
        ),
    ]
