# Generated by Django 2.1.7 on 2020-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0061_auto_20200212_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costtimels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0', models.IntegerField()),
                ('id1', models.IntegerField()),
                ('timels', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
