# Generated by Django 2.1.7 on 2020-02-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0062_costtimels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Daticontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onoff', models.IntegerField(default=0)),
            ],
        ),
    ]
