# Generated by Django 2.1.7 on 2020-02-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0063_dati_daticontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datirecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('xx', models.CharField(max_length=50)),
            ],
        ),
    ]
