# Generated by Django 2.1.7 on 2020-03-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0069_address1_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kzlogin',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
