# Generated by Django 2.1.7 on 2020-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0071_auto_20200313_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kzlogin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kzonoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onoff', models.IntegerField()),
            ],
        ),
    ]
