# Generated by Django 2.1.7 on 2020-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0072_kzlogin1_kzonoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kzidrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
