# Generated by Django 2.1.7 on 2020-09-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0073_kzidrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuxinamezk',
            name='bj',
            field=models.IntegerField(default=0),
        ),
    ]
