# Generated by Django 2.1.7 on 2020-09-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0074_yuxinamezk_bj'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnames',
            name='bj',
            field=models.IntegerField(default=0),
        ),
    ]
