# Generated by Django 2.1.7 on 2020-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0075_newnames_bj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('questionid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='classnotes',
            name='bans',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
