# Generated by Django 2.1.7 on 2020-10-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0076_auto_20201001_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuoti',
            new_name='Wrongqs',
        ),
    ]
