# Generated by Django 2.1.7 on 2020-11-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0079_auto_20201123_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badnews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('hwname', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='homeworksid',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='homeworks',
            name='stuid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworksid',
            name='hwname',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
