# Generated by Django 2.1.7 on 2020-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0080_auto_20201125_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('reason', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Uselucky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('num', models.IntegerField()),
                ('ornot', models.IntegerField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
