# Generated by Django 2.1.7 on 2020-11-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0082_auto_20201126_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setgoodns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('num', models.IntegerField()),
                ('reason', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='uselucky',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
