# Generated by Django 2.1.7 on 2020-12-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0085_luckys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
