# Generated by Django 2.1.7 on 2020-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0086_classnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardqs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.ImageField(upload_to='hardquestions')),
                ('questionanswer', models.CharField(max_length=50)),
                ('ornot', models.IntegerField(default=0)),
                ('ornots', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('killer', models.CharField(max_length=50)),
                ('nums', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ornot'],
            },
        ),
        migrations.CreateModel(
            name='Hardqsrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
