# Generated by Django 2.1.7 on 2020-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0087_hardqs_hardqsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardqs',
            name='jihui',
            field=models.IntegerField(default=2),
        ),
    ]
