# Generated by Django 2.1.7 on 2020-12-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0088_hardqs_jihui'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardqs',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='luckys',
            name='clas',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='setgoodns',
            name='clas',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='uselucky',
            name='clas',
            field=models.IntegerField(default=3),
        ),
    ]
