# Generated by Django 2.1.7 on 2020-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0089_auto_20201203_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardqs',
            name='killer4',
            field=models.CharField(default=33, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardqs',
            name='ornot4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hardqs',
            name='ornots4',
            field=models.CharField(default=33, max_length=50),
            preserve_default=False,
        ),
    ]
