# Generated by Django 2.1.7 on 2020-12-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0090_auto_20201203_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardqsname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('clas', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
