# Generated by Django 2.1.7 on 2020-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0092_hardqs_answerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardkilleronoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard', models.IntegerField(default=1)),
                ('middle', models.IntegerField(default=1)),
                ('easy', models.IntegerField(default=1)),
            ],
        ),
    ]
