# Generated by Django 2.1.7 on 2020-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0094_easyqslimit_hardqslimit_middleqslimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Easyqs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questiontext', models.ImageField(upload_to='easyqs')),
                ('questionanswer', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Easyrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('clas', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
