# Generated by Django 2.1.7 on 2020-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0095_easyqs_easyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('num', models.IntegerField()),
                ('pl', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
