# Generated by Django 2.1.7 on 2020-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0097_auto_20201210_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardqsrecord',
            name='ornot',
            field=models.IntegerField(default=0),
        ),
    ]
