# Generated by Django 2.1.7 on 2020-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0099_jifeng_jifengrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='jifengrecord',
            name='clas',
            field=models.IntegerField(default=0),
        ),
    ]
