# Generated by Django 2.1.7 on 2020-12-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0102_homeworks_ornots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homewrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hwname', models.IntegerField()),
                ('qk', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('times', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
