# Generated by Django 2.1.7 on 2020-12-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0103_homewrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewrecord',
            name='hwname',
            field=models.CharField(max_length=50),
        ),
    ]
