# Generated by Django 2.1.7 on 2020-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0107_musics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zslimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
