# Generated by Django 2.1.7 on 2020-12-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0108_zslimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('clas', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
