# Generated by Django 2.1.7 on 2020-12-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0109_sumrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
