# Generated by Django 2.1.7 on 2020-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0111_getlucky_getluckynames_getluckyornot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hweveryday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwname', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=500)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hweverydayrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwname', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=500)),
                ('num', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('clas', models.IntegerField(default=0)),
                ('ornot', models.CharField(max_length=50)),
                ('times', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Studentids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('idd', models.IntegerField()),
                ('clas', models.IntegerField()),
            ],
        ),
    ]
