# Generated by Django 2.1.7 on 2021-03-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylearn', '0113_paotui'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mintest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtime', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sumscore', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('idd', models.IntegerField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Mintestdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testtime', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('sumscore', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('idd', models.IntegerField()),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('clas', models.IntegerField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Mintestrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('idd', models.IntegerField()),
                ('clas', models.IntegerField()),
                ('sumscore', models.IntegerField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='homeworks',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeworksid',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
